# Generated by Django 2.2 on 2020-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveacc',
            name='savetype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
