# Generated by Django 2.2 on 2020-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200610_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(related_name='loan_cus', through='manager.CusForLoan', to='manager.Customer'),
        ),
    ]
