# Generated by Django 2.2 on 2020-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200610_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='moneyleft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(related_name='loan_cus', through='manager.CusForLoan', to='manager.Customer'),
        ),
    ]
