# Generated by Django 3.0.3 on 2020-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200610_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(related_name='loan_cus', through='manager.CusForLoan', to='manager.Customer'),
        ),
    ]
