# Generated by Django 3.0.7 on 2020-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200621_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(related_name='loan_cus', through='manager.CusForLoan', to='manager.Customer'),
        ),
    ]
